In [1]:
import pandas as pd
import numpy as np

In [2]:
var={'a':120,'b':130,'c':140}
svar=pd.Series(var)

In [4]:
svar.index

Index(['a', 'b', 'c'], dtype='object')

In [8]:
svar['d']=150

In [16]:
svar

a    120
b    130
c    140
d    150
dtype: int64

In [17]:
svar[svar>=130]

b    130
c    140
d    150
dtype: int64

In [22]:
svar.index.name='abc'

In [23]:
svar

abc
a    120
b    130
c    140
d    150
dtype: int64

In [24]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
"year": [2000, 2001, 2002, 2001, 2002, 2003],
"pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [33]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [32]:
pd.DataFrame(data,columns=['pop','year','state'])

   pop  year   state
0  1.5  2000    Ohio
1  1.7  2001    Ohio
2  3.6  2002    Ohio
3  2.4  2001  Nevada
4  2.9  2002  Nevada
5  3.2  2003  Nevada

In [35]:
svar

abc
a    120
b    130
c    140
d    150
dtype: int64

In [36]:
 frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])

In [37]:
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [4]:
labels=pd.Index(np.arange(3))

In [5]:
labels

Index([0, 1, 2], dtype='int32')

In [8]:
obj2=pd.Series(['Shaka',2,3], index=labels)

In [9]:
obj2

0    Shaka
1        2
2        3
dtype: object

In [15]:
labels

Index([0, 1, 2], dtype='int32')

In [16]:
obj=pd.Series([1,2,3,4,5], index=["a","b","c","d","e"])

In [18]:
obj2=obj.reindex(["c","d","e","a","b"])

In [19]:
obj2

c    3
d    4
e    5
a    1
b    2
dtype: int64

In [23]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])

In [24]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [25]:
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [18]:
frame = pd.DataFrame(np.arange(16).reshape((4, 4)),index=["a", "c", "d", "e"],columns=["Ohio", "Texas", "California", "Georgia"])

In [27]:
frame

   Ohio  Texas  California  Georgia
a     0      1           2        3
c     4      5           6        7
d     8      9          10       11
e    12     13          14       15

In [29]:
frame.pop('Georgia')

a     3
c     7
d    11
e    15
Name: Georgia, dtype: int32

In [33]:
frame2=frame.reindex(["a","b","c","d","e"])

In [35]:
frame2*frame

    Ohio  Texas  California
a    0.0    1.0         4.0
b    NaN    NaN         NaN
c   16.0   25.0        36.0
d   64.0   81.0       100.0
e  144.0  169.0       196.0

In [36]:
states = ["Texas", "Utah", "California"]

In [37]:
frame.reindex(columns=states)

   Texas  Utah  California
a      1   NaN           2
c      5   NaN           6
d      9   NaN          10
e     13   NaN          14

In [2]:
s=pd.Series(np.arange(5))

In [14]:
labels=s.axes

In [13]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [15]:
labels[0]

RangeIndex(start=0, stop=5, step=1)

In [25]:
s.empty

False

In [17]:
s.ndim

1

In [19]:
frame.ndim

2

In [20]:
s.size

5

In [21]:
frame.size

16

In [26]:
s.values

array([0, 1, 2, 3, 4])

In [27]:
frame.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
df=pd.read_csv(r'employees_messy.csv')

In [32]:
list=df.values

In [35]:
list[4]

array(['EMP134', 'ahmed', 'Akhtar', 'M', nan, '06-21-2020', 'sales',
       'islamabad', nan, '03348959963', nan, nan, nan], dtype=object)

In [39]:
df.head(5)

,Employee_ID,First_Name,Last_Name,Gender,Age,Join_Date,Department,City,Salary_PKR,Phone,Email,Performance_Score,Unnamed: 12
0,EMP 0113,hassan,Qureshi,m,45 yrs,06-13-2022,finance,islamabad,NaN,03323308823,missing,5,NaN
1,EMP 0055,FATIMA,AHMED,f,NaN,03-Jan-20,IT,karachi,PKR 119892,-9122210,FATIMA.AHMED@HOTMAIL.COM,NaN,NaN
2,EMP0158,ahmed,chaudhry,Male,NaN,22-04-20,H.R,rawalpindi,80720,NaN,missing,NaN,NaN
3,emp0136,Ali,chaudhry,female,28,11-20-2022,sales,Rawalpindi,140154,NaN,ali.chaudhry @ gmail.com,5,NaN
4,EMP134,ahmed,Akhtar,M,NaN,06-21-2020,sales,islamabad,NaN,03348959963,NaN,NaN,NaN

In [43]:
df.shape

(210, 13)

In [44]:
210*13

2730

In [45]:
df.size

2730

In [57]:
frame

   Ohio  Texas  California  Georgia
a     0      1           2        3
c     4      5           6        7
d     8      9          10       11
e    12     13          14       15

In [59]:
frame.sum(0)

Ohio          24
Texas         28
California    32
Georgia       36
dtype: int64

In [61]:
frame.mean(1)

a     1.5
c     5.5
d     9.5
e    13.5
dtype: float64

In [62]:
frame.iloc[0].mean()

1.5

In [63]:
frame.cumsum()

   Ohio  Texas  California  Georgia
a     0      1           2        3
c     4      6           8       10
d    12     15          18       21
e    24     28          32       36

In [64]:
df.count()

Employee_ID          210
First_Name           210
Last_Name            210
Gender               210
Age                  118
Join_Date            210
Department           210
City                 210
Salary_PKR           148
Phone                155
Email                145
Performance_Score    115
Unnamed: 12            0
dtype: int64

In [65]:
frame.cumprod()

   Ohio  Texas  California  Georgia
a     0      1           2        3
c     0      5          12       21
d     0     45         120      231
e     0    585        1680     3465

In [66]:
frame.abs()

   Ohio  Texas  California  Georgia
a     0      1           2        3
c     4      5           6        7
d     8      9          10       11
e    12     13          14       15

In [86]:
list=frame.columns

In [92]:
list[:]

Index(['Ohio', 'Texas', 'California', 'Georgia'], dtype='object')