In [1]:
import pandas as pd
import numpy as np

In [2]:
var={'a':120,'b':130,'c':140}
svar=pd.Series(var)

In [4]:
svar.index

Index(['a', 'b', 'c'], dtype='object')

In [8]:
svar['d']=150

In [16]:
svar

a    120
b    130
c    140
d    150
dtype: int64

In [17]:
svar[svar>=130]

b    130
c    140
d    150
dtype: int64

In [22]:
svar.index.name='abc'

In [23]:
svar

abc
a    120
b    130
c    140
d    150
dtype: int64

In [24]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
"year": [2000, 2001, 2002, 2001, 2002, 2003],
"pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [33]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [32]:
pd.DataFrame(data,columns=['pop','year','state'])

   pop  year   state
0  1.5  2000    Ohio
1  1.7  2001    Ohio
2  3.6  2002    Ohio
3  2.4  2001  Nevada
4  2.9  2002  Nevada
5  3.2  2003  Nevada

In [35]:
svar

abc
a    120
b    130
c    140
d    150
dtype: int64

In [36]:
 frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])

In [37]:
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [4]:
labels=pd.Index(np.arange(3))

In [5]:
labels

Index([0, 1, 2], dtype='int32')

In [8]:
obj2=pd.Series(['Shaka',2,3], index=labels)

In [9]:
obj2

0    Shaka
1        2
2        3
dtype: object

In [15]:
labels

Index([0, 1, 2], dtype='int32')

In [16]:
obj=pd.Series([1,2,3,4,5], index=["a","b","c","d","e"])

In [18]:
obj2=obj.reindex(["c","d","e","a","b"])

In [19]:
obj2

c    3
d    4
e    5
a    1
b    2
dtype: int64

In [23]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])

In [24]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [25]:
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [18]:
frame = pd.DataFrame(np.arange(16).reshape((4, 4)),index=["a", "c", "d", "e"],columns=["Ohio", "Texas", "California", "Georgia"])

In [27]:
frame

   Ohio  Texas  California  Georgia
a     0      1           2        3
c     4      5           6        7
d     8      9          10       11
e    12     13          14       15

In [29]:
frame.pop('Georgia')

a     3
c     7
d    11
e    15
Name: Georgia, dtype: int32

In [33]:
frame2=frame.reindex(["a","b","c","d","e"])

In [35]:
frame2*frame

    Ohio  Texas  California
a    0.0    1.0         4.0
b    NaN    NaN         NaN
c   16.0   25.0        36.0
d   64.0   81.0       100.0
e  144.0  169.0       196.0

In [36]:
states = ["Texas", "Utah", "California"]

In [37]:
frame.reindex(columns=states)

   Texas  Utah  California
a      1   NaN           2
c      5   NaN           6
d      9   NaN          10
e     13   NaN          14

In [2]:
s=pd.Series(np.arange(5))

In [14]:
labels=s.axes

In [13]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [15]:
labels[0]

RangeIndex(start=0, stop=5, step=1)

In [25]:
s.empty

False

In [17]:
s.ndim

1

In [19]:
frame.ndim

2

In [20]:
s.size

5

In [21]:
frame.size

16

In [26]:
s.values

array([0, 1, 2, 3, 4])

In [27]:
frame.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
df=pd.read_csv(r'C:\Users\PMLS\Desktop\Untitled Folder\employees_messy.csv')

In [32]:
list=df.values

In [35]:
list[4]

array(['EMP134', 'ahmed', 'Akhtar', 'M', nan, '06-21-2020', 'sales',
       'islamabad', nan, '03348959963', nan, nan, nan], dtype=object)

In [39]:
df.head(5)

,Employee_ID,First_Name,Last_Name,Gender,Age,Join_Date,Department,City,Salary_PKR,Phone,Email,Performance_Score,Unnamed: 12
0,EMP 0113,hassan,Qureshi,m,45 yrs,06-13-2022,finance,islamabad,NaN,03323308823,missing,5,NaN
1,EMP 0055,FATIMA,AHMED,f,NaN,03-Jan-20,IT,karachi,PKR 119892,-9122210,FATIMA.AHMED@HOTMAIL.COM,NaN,NaN
2,EMP0158,ahmed,chaudhry,Male,NaN,22-04-20,H.R,rawalpindi,80720,NaN,missing,NaN,NaN
3,emp0136,Ali,chaudhry,female,28,11-20-2022,sales,Rawalpindi,140154,NaN,ali.chaudhry @ gmail.com,5,NaN
4,EMP134,ahmed,Akhtar,M,NaN,06-21-2020,sales,islamabad,NaN,03348959963,NaN,NaN,NaN

In [43]:
df.shape

(210, 13)

In [44]:
210*13

2730

In [45]:
df.size

2730

In [57]:
frame

   Ohio  Texas  California  Georgia
a     0      1           2        3
c     4      5           6        7
d     8      9          10       11
e    12     13          14       15

In [59]:
frame.sum(0)

Ohio          24
Texas         28
California    32
Georgia       36
dtype: int64

In [61]:
frame.mean(1)

a     1.5
c     5.5
d     9.5
e    13.5
dtype: float64

In [62]:
frame.iloc[0].mean()

1.5

In [63]:
frame.cumsum()

   Ohio  Texas  California  Georgia
a     0      1           2        3
c     4      6           8       10
d    12     15          18       21
e    24     28          32       36

In [64]:
df.count()

Employee_ID          210
First_Name           210
Last_Name            210
Gender               210
Age                  118
Join_Date            210
Department           210
City                 210
Salary_PKR           148
Phone                155
Email                145
Performance_Score    115
Unnamed: 12            0
dtype: int64

In [65]:
frame.cumprod()

   Ohio  Texas  California  Georgia
a     0      1           2        3
c     0      5          12       21
d     0     45         120      231
e     0    585        1680     3465

In [66]:
frame.abs()

   Ohio  Texas  California  Georgia
a     0      1           2        3
c     4      5           6        7
d     8      9          10       11
e    12     13          14       15

In [86]:
list=frame.columns

In [92]:
list[:]

Index(['Ohio', 'Texas', 'California', 'Georgia'], dtype='object')

In [1]:
import pandas as pd
import numpy as np

In [2]:
def adder(e1,e2):
    return e1+e2
df=pd.DataFrame(np.random.randn(5,3),columns=['col1','col2','col3'])
df.pipe(adder,2)

       col1      col2      col3
0 -1.306546  2.182610  4.892028
1  2.710328  3.207094  1.029415
2  1.294774  2.870304  2.309574
3  2.112384  1.609122  2.568311
4  2.546668  2.640664  1.731462

In [3]:
df

       col1      col2      col3
0 -3.306546  0.182610  2.892028
1  0.710328  1.207094 -0.970585
2 -0.705226  0.870304  0.309574
3  0.112384 -0.390878  0.568311
4  0.546668  0.640664 -0.268538

In [3]:
pd

#pandas reindexing

In [7]:
pd.date_range(start='01-01-2026', periods=20, freq='D')

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06', '2026-01-07', '2026-01-08',
               '2026-01-09', '2026-01-10', '2026-01-11', '2026-01-12',
               '2026-01-13', '2026-01-14', '2026-01-15', '2026-01-16',
               '2026-01-17', '2026-01-18', '2026-01-19', '2026-01-20'],
              dtype='datetime64[ns]', freq='D')

In [2]:
#pandas reindexing

In [3]:
#.reindex(index=[],column=[])
#.reindex_like(df1,method=ffill,limit=2)

In [11]:
df=pd.read_csv(r'dataset/Employees.csv')

In [9]:
df['City']=df['City'].map({'Multan':'M'})

In [13]:
df.sample(5)

,Sales_Rep_ID,Employee_Name,Department,City,Hire_Date,Salary
77,EMP0078,Jeff Hill,Sales,Abu Dhabi,12-31-2020,82500.0
16,EMP0017,Devin Schaefer,Customer Support,Mecca,12-16-2021,64700.0
26,EMP0027,Julie King,Logistics,Dammam,25/10/2023,61200.0
67,EMP0068,Timothy Walls,Sales,Medina,02-14-2023,115100.0
49,EMP0050,James Morgan,Customer Support,Peshawar,24/01/2026,45900.0

In [36]:
# for column, data in df.items():
#     print(column)
#     print(data)
for col, values in df.head(5).items():
    print(f"{col}: {values}")

Sales_Rep_ID: 0    EMP0001
1    EMP0002
2    EMP0003
3    EMP0004
4    EMP0005
Name: Sales_Rep_ID, dtype: object
Employee_Name: 0    Patrick Sanchez
1      Megan Mcclain
2       Amanda Davis
3    Alyssa Gonzalez
4      Jennifer Cole
Name: Employee_Name, dtype: object
Department: 0           Marketing
1    Customer Support
2           Marketing
3               Sales
4           Marketing
Name: Department, dtype: object
City: 0       Multan
1    Abu Dhabi
2      Karachi
3       Dammam
4       Riyadh
Name: City, dtype: object
Hire_Date: 0     01-03-2026
1     10-03-2021
2     04-23-2021
3    19-Jul-2022
4     02-05-2026
Name: Hire_Date, dtype: object
Salary: 0    102400.0
1     86500.0
2    106200.0
3    128100.0
4     84100.0
Name: Salary, dtype: float64

In [35]:
for index, row in df.head(5).iterrows():
    print(index)
    print(row)

0
Sales_Rep_ID             EMP0001
Employee_Name    Patrick Sanchez
Department             Marketing
City                      Multan
Hire_Date             01-03-2026
Salary                  102400.0
Name: 0, dtype: object
1
Sales_Rep_ID              EMP0002
Employee_Name       Megan Mcclain
Department       Customer Support
City                    Abu Dhabi
Hire_Date              10-03-2021
Salary                    86500.0
Name: 1, dtype: object
2
Sales_Rep_ID          EMP0003
Employee_Name    Amanda Davis
Department          Marketing
City                  Karachi
Hire_Date          04-23-2021
Salary               106200.0
Name: 2, dtype: object
3
Sales_Rep_ID             EMP0004
Employee_Name    Alyssa Gonzalez
Department                 Sales
City                      Dammam
Hire_Date            19-Jul-2022
Salary                  128100.0
Name: 3, dtype: object
4
Sales_Rep_ID           EMP0005
Employee_Name    Jennifer Cole
Department           Marketing
City                    Riyadh
Hire_Date           02-05-2026
Salary                 84100.0
Name: 4, dtype: object

In [34]:
for index, row in df.head(5).iterrows():
    print(f"{index}{row['Employee_Name']}||{row['City']}")

0Patrick Sanchez||Multan
1Megan Mcclain||Abu Dhabi
2Amanda Davis||Karachi
3Alyssa Gonzalez||Dammam
4Jennifer Cole||Riyadh

In [38]:
for row in df.head(5).itertuples():
    print(row)

Pandas(Index=0, Sales_Rep_ID='EMP0001', Employee_Name='Patrick Sanchez', Department='Marketing', City='Multan', Hire_Date='01-03-2026', Salary=102400.0)
Pandas(Index=1, Sales_Rep_ID='EMP0002', Employee_Name='Megan Mcclain', Department='Customer Support', City='Abu Dhabi', Hire_Date='10-03-2021', Salary=86500.0)
Pandas(Index=2, Sales_Rep_ID='EMP0003', Employee_Name='Amanda Davis', Department='Marketing', City='Karachi', Hire_Date='04-23-2021', Salary=106200.0)
Pandas(Index=3, Sales_Rep_ID='EMP0004', Employee_Name='Alyssa Gonzalez', Department='Sales', City='Dammam', Hire_Date='19-Jul-2022', Salary=128100.0)
Pandas(Index=4, Sales_Rep_ID='EMP0005', Employee_Name='Jennifer Cole', Department='Marketing', City='Riyadh', Hire_Date='02-05-2026', Salary=84100.0)

In [39]:
for index, row in df.iterrows():
    df.loc[index, 'Tax'] = row['Salary'] * 0.10

In [46]:
df[['Tax','Salary']].head(5)

       Tax    Salary
0  10240.0  102400.0
1   8650.0   86500.0
2  10620.0  106200.0
3  12810.0  128100.0
4   8410.0   84100.0

In [48]:
df.sort_index(ascending=False).head(5)

,Sales_Rep_ID,Employee_Name,Department,City,Hire_Date,Salary,Tax
101,EMP0054,Kimberly Smith,Marketing,Medina,31/12/2020,105300.0,10530.0
100,EMP0084,Christine Wright,Marketing,Riyadh,27-Nov-2020,77000.0,7700.0
99,EMP0100,Kimberly Ball,Customer Support,Ajman,28-Dec-2024,84100.0,8410.0
98,EMP0099,Andrew Graham,Warehouse Operations,Medina,22-Jun-2025,90100.0,9010.0
97,EMP0098,William Wilson,Warehouse Operations,Dubai,28-Mar-2023,96500.0,9650.0

In [56]:
df.sort_values(by='Salary', ascending=False, kind='mergesort').head()

,Sales_Rep_ID,Employee_Name,Department,City,Hire_Date,Salary,Tax
31,EMP0032,Elizabeth Fowler,Sales,Riyadh,2021-06-22,136300.0,13630.0
6,EMP0007,Christopher Bernard,Sales,Riyadh,03-01-2024,129500.0,12950.0
73,EMP0074,Shawn Baker,Warehouse Operations,Karachi,03-19-2026,129100.0,12910.0
71,EMP0072,Joshua Turner,Logistics,Dammam,29-Nov-2021,128500.0,12850.0
3,EMP0004,Alyssa Gonzalez,Sales,Dammam,19-Jul-2022,128100.0,12810.0

In [78]:
df['Employee_Name'].str.strip().head(5).str.len()

0    15
1    13
2    12
3    15
4    13
Name: Employee_Name, dtype: int64

In [80]:
df['Employee_Name'].head(5).str.len()

0    15
1    13
2    12
3    15
4    13
Name: Employee_Name, dtype: int64

In [85]:
df1=df['Employee_Name'].str.split(' ').head()

In [87]:
df1[1][1]

'Mcclain'

In [91]:
df['Employee_Name'].str.cat(df['Salary'].astype(str), sep='-').head()

0    Patrick Sanchez-102400.0
1       Megan Mcclain-86500.0
2       Amanda Davis-106200.0
3    Alyssa Gonzalez-128100.0
4       Jennifer Cole-84100.0
Name: Employee_Name, dtype: object

In [101]:
df.columns=df.columns.str.replace('-','_')

In [102]:
df.head()

,sales_rep_id,employee_name,department,city,hire_date,salary,tax
0,EMP0001,Patrick Sanchez,Marketing,Multan,01-03-2026,102400.0,10240.0
1,EMP0002,Megan Mcclain,Customer Support,Abu Dhabi,10-03-2021,86500.0,8650.0
2,EMP0003,Amanda Davis,Marketing,Karachi,04-23-2021,106200.0,10620.0
3,EMP0004,Alyssa Gonzalez,Sales,Dammam,19-Jul-2022,128100.0,12810.0
4,EMP0005,Jennifer Cole,Marketing,Riyadh,02-05-2026,84100.0,8410.0

In [105]:
df['employee_name'].str.repeat(2).head()

0    Patrick SanchezPatrick Sanchez
1        Megan McclainMegan Mcclain
2          Amanda DavisAmanda Davis
3    Alyssa GonzalezAlyssa Gonzalez
4        Jennifer ColeJennifer Cole
Name: employee_name, dtype: object

In [123]:
df['salary'].sort_values(ascending=False).astype(str).str.startswith('1').head()

31    True
6     True
73    True
71    True
3     True
Name: salary, dtype: bool

In [118]:
df.sort_values(by='salary', ascending=False)

,sales_rep_id,employee_name,department,city,hire_date,salary,tax
31,EMP0032,Elizabeth Fowler,Sales,Riyadh,2021-06-22,136300.0,13630.0
6,EMP0007,Christopher Bernard,Sales,Riyadh,03-01-2024,129500.0,12950.0
73,EMP0074,Shawn Baker,Warehouse Operations,Karachi,03-19-2026,129100.0,12910.0
71,EMP0072,Joshua Turner,Logistics,Dammam,29-Nov-2021,128500.0,12850.0
3,EMP0004,Alyssa Gonzalez,Sales,Dammam,19-Jul-2022,128100.0,12810.0
...,...,...,...,...,...,...,...
49,EMP0050,James Morgan,Customer Support,Peshawar,24/01/2026,45900.0,4590.0
13,EMP0014,Holly Wood,Sales,Lahore,04-Jun-2024,42200.0,4220.0
37,EMP0038,Betty Alvarez,Sales,Jeddah,2025-02-06,41000.0,4100.0
79,EMP0080,Kristen Patterson,Warehouse Operations,Riyadh,11-Dec-2021,40300.0,4030.0
74,EMP0075,Brittney Campbell,Marketing,Multan,24-Jun-2021,30000.0,3000.0

In [125]:
df['employee_name'].str.find('e').head()

0    13
1     1
2    -1
3    13
4     1
Name: employee_name, dtype: int64

In [129]:
df['employee_name'].str.findall('e').head()

0          [e]
1          [e]
2           []
3          [e]
4    [e, e, e]
Name: employee_name, dtype: object

In [130]:
df['employee_name'].str.swapcase().head()

0    pATRICK sANCHEZ
1      mEGAN mCCLAIN
2       aMANDA dAVIS
3    aLYSSA gONZALEZ
4      jENNIFER cOLE
Name: employee_name, dtype: object

In [133]:
 df['department'].str.get_dummies().sample(10)

    Customer Support  Logistics  Marketing  Sales  Warehouse Operations
13                 0          0          0      1                     0
39                 0          0          0      0                     1
96                 1          0          0      0                     0
21                 0          0          1      0                     0
67                 0          0          0      1                     0
56                 0          1          0      0                     0
88                 0          0          0      0                     1
85                 1          0          0      0                     0
5                  0          0          0      0                     1
6                  0          0          0      1                     0

In [146]:
for index, rows in df.head(2).iterrows():
    print(f"{index} , {rows}")

0 , sales_rep_id             EMP0001
employee_name    Patrick Sanchez
department             Marketing
city                      Multan
hire_date             01-03-2026
salary                  102400.0
tax                      10240.0
Name: 0, dtype: object
1 , sales_rep_id              EMP0002
employee_name       Megan Mcclain
department       Customer Support
city                    Abu Dhabi
hire_date              10-03-2021
salary                    86500.0
tax                        8650.0
Name: 1, dtype: object

In [1]:
import pandas as pd
import numpy as np

In [7]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], index=['a','b','c'],columns=['one','two','three'])

In [8]:
df

   one  two  three
a    1    2      3
b    4    5      6
c    7    8      9

In [15]:
pd.set_option("display.max_rows",10)

In [16]:
pd.get_option("display.max_rows")

10

In [17]:
df

,Employee_ID,First_Name,Last_Name,Gender,Age,Join_Date,Department,City,Salary_PKR,Phone,Email,Performance_Score,Unnamed: 12
0,EMP 0113,hassan,Qureshi,m,45 yrs,06-13-2022,finance,islamabad,NaN,03323308823,missing,5,NaN
1,EMP 0055,FATIMA,AHMED,f,NaN,03-Jan-20,IT,karachi,PKR 119892,-9122210,FATIMA.AHMED@HOTMAIL.COM,NaN,NaN
2,EMP0158,ahmed,chaudhry,Male,NaN,22-04-20,H.R,rawalpindi,80720,NaN,missing,NaN,NaN
3,emp0136,Ali,chaudhry,female,28,11-20-2022,sales,Rawalpindi,140154,NaN,ali.chaudhry @ gmail.com,5,NaN
4,EMP134,ahmed,Akhtar,M,NaN,06-21-2020,sales,islamabad,NaN,03348959963,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,emp0130,bilal,Khan,M,38,11-07-20,Finance,Islamabad,"148,092",0349-3270167,bilal. khan@outlook. com,NaN,NaN
206,EMP108,bilal,Khan,female,23 yrs,06-20-2020,it,karachi,NaN,0313-8763551,BILAL.KHAN@OUTLOOK.COM,NaN,NaN
207,EMP0095,bilal,AHMED,Male,NaN,02-Jan-23,FINANCE,LAHORE,81728,03222924992,bilal. ahmed@hotmail. com,not rated,NaN
208,EMP 0046,FATIMA,butt,Male,27 yrs,16-02-22,sales,KARACHI,"125,562",NaN,FATIMA.BUTT@GMAIL.COM,not rated,NaN
209,EMP0126,Zara,chaudhry,female,34 yrs,29-09-23,marketing,lahore,148816,0329-4115268,missing,1,NaN

In [18]:
pd.describe_option('display.max_rows')

display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: 10]

In [24]:
with pd.option_context(
'display.max_rows', 10,
'display.max_columns',None):
    print(df)

    Employee_ID First_Name Last_Name  Gender     Age   Join_Date Department  \
0      EMP 0113     hassan   Qureshi       m  45 yrs  06-13-2022    finance
1      EMP 0055     FATIMA     AHMED       f     NaN   03-Jan-20         IT
2       EMP0158      ahmed  chaudhry    Male     NaN    22-04-20        H.R
3       emp0136        Ali  chaudhry  female      28  11-20-2022      sales
4        EMP134      ahmed    Akhtar       M     NaN  06-21-2020      sales
..          ...        ...       ...     ...     ...         ...        ...
205     emp0130      bilal      Khan       M      38    11-07-20    Finance
206      EMP108      bilal      Khan  female  23 yrs  06-20-2020         it
207     EMP0095      bilal     AHMED    Male     NaN   02-Jan-23    FINANCE
208    EMP 0046     FATIMA      butt    Male  27 yrs    16-02-22      sales
209     EMP0126       Zara  chaudhry  female  34 yrs    29-09-23  marketing

           City  Salary_PKR         Phone                      Email  \
0     islamabad         NaN   03323308823                    missing
1       karachi  PKR 119892      -9122210   FATIMA.AHMED@HOTMAIL.COM
2    rawalpindi       80720           NaN                    missing
3    Rawalpindi      140154           NaN   ali.chaudhry @ gmail.com
4     islamabad         NaN   03348959963                        NaN
..          ...         ...           ...                        ...
205   Islamabad     148,092  0349-3270167   bilal. khan@outlook. com
206     karachi         NaN  0313-8763551     BILAL.KHAN@OUTLOOK.COM
207      LAHORE       81728   03222924992  bilal. ahmed@hotmail. com
208     KARACHI     125,562           NaN      FATIMA.BUTT@GMAIL.COM
209      lahore      148816  0329-4115268                    missing

    Performance_Score  Unnamed: 12
0                   5          NaN
1                 NaN          NaN
2                 NaN          NaN
3                   5          NaN
4                 NaN          NaN
..                ...          ...
205               NaN          NaN
206               NaN          NaN
207         not rated          NaN
208         not rated          NaN
209                 1          NaN

[210 rows x 13 columns]

Indexing and Selecting Data

In [42]:
df

,Employee_ID,First_Name,Last_Name,Gender,Age,Join_Date,Department,City,Salary_PKR,Phone,Email,Performance_Score,Unnamed: 12
0,EMP 0113,hassan,Qureshi,m,45 yrs,06-13-2022,finance,islamabad,NaN,03323308823,missing,5,NaN
1,EMP 0055,FATIMA,AHMED,f,NaN,03-Jan-20,IT,karachi,PKR 119892,-9122210,FATIMA.AHMED@HOTMAIL.COM,NaN,NaN
2,EMP0158,ahmed,chaudhry,Male,NaN,22-04-20,H.R,rawalpindi,80720,NaN,missing,NaN,NaN
3,emp0136,Ali,chaudhry,female,28,11-20-2022,sales,Rawalpindi,140154,NaN,ali.chaudhry @ gmail.com,5,NaN
4,EMP134,ahmed,Akhtar,M,NaN,06-21-2020,sales,islamabad,NaN,03348959963,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,emp0130,bilal,Khan,M,38,11-07-20,Finance,Islamabad,"148,092",0349-3270167,bilal. khan@outlook. com,NaN,NaN
206,EMP108,bilal,Khan,female,23 yrs,06-20-2020,it,karachi,NaN,0313-8763551,BILAL.KHAN@OUTLOOK.COM,NaN,NaN
207,EMP0095,bilal,AHMED,Male,NaN,02-Jan-23,FINANCE,LAHORE,81728,03222924992,bilal. ahmed@hotmail. com,not rated,NaN
208,EMP 0046,FATIMA,butt,Male,27 yrs,16-02-22,sales,KARACHI,"125,562",NaN,FATIMA.BUTT@GMAIL.COM,not rated,NaN
209,EMP0126,Zara,chaudhry,female,34 yrs,29-09-23,marketing,lahore,148816,0329-4115268,missing,1,NaN

In [38]:
pd.set_option("display.max_rows",50)

In [34]:
df.columns

Index(['Employee_ID', 'First_Name', 'Last_Name', 'Gender', 'Age', 'Join_Date',
       'Department', 'City', 'Salary_PKR', 'Phone', 'Email',
       'Performance_Score', 'Unnamed: 12'],
      dtype='object')

In [50]:
pd.set_option("display.max_rows",10)

In [47]:
pd.get_option("display.max_rows")

200

In [51]:
print(df)

    Employee_ID First_Name Last_Name  Gender     Age   Join_Date Department  \
0      EMP 0113     hassan   Qureshi       m  45 yrs  06-13-2022    finance
1      EMP 0055     FATIMA     AHMED       f     NaN   03-Jan-20         IT
2       EMP0158      ahmed  chaudhry    Male     NaN    22-04-20        H.R
3       emp0136        Ali  chaudhry  female      28  11-20-2022      sales
4        EMP134      ahmed    Akhtar       M     NaN  06-21-2020      sales
..          ...        ...       ...     ...     ...         ...        ...
205     emp0130      bilal      Khan       M      38    11-07-20    Finance
206      EMP108      bilal      Khan  female  23 yrs  06-20-2020         it
207     EMP0095      bilal     AHMED    Male     NaN   02-Jan-23    FINANCE
208    EMP 0046     FATIMA      butt    Male  27 yrs    16-02-22      sales
209     EMP0126       Zara  chaudhry  female  34 yrs    29-09-23  marketing

           City  Salary_PKR         Phone                      Email  \
0     islamabad         NaN   03323308823                    missing
1       karachi  PKR 119892      -9122210   FATIMA.AHMED@HOTMAIL.COM
2    rawalpindi       80720           NaN                    missing
3    Rawalpindi      140154           NaN   ali.chaudhry @ gmail.com
4     islamabad         NaN   03348959963                        NaN
..          ...         ...           ...                        ...
205   Islamabad     148,092  0349-3270167   bilal. khan@outlook. com
206     karachi         NaN  0313-8763551     BILAL.KHAN@OUTLOOK.COM
207      LAHORE       81728   03222924992  bilal. ahmed@hotmail. com
208     KARACHI     125,562           NaN      FATIMA.BUTT@GMAIL.COM
209      lahore      148816  0329-4115268                    missing

    Performance_Score  Unnamed: 12
0                   5          NaN
1                 NaN          NaN
2                 NaN          NaN
3                   5          NaN
4                 NaN          NaN
..                ...          ...
205               NaN          NaN
206               NaN          NaN
207         not rated          NaN
208         not rated          NaN
209                 1          NaN

[210 rows x 13 columns]

In [53]:
df.iloc[:4,1:3]

  First_Name Last_Name
0     hassan   Qureshi
1     FATIMA     AHMED
2      ahmed  chaudhry
3        Ali  chaudhry

In [62]:
df['Full_Name']=df['First_Name'].str.cat(df['Last_Name'],'-')

In [63]:
df['Full_Name']

0      hassan-Qureshi
1        FATIMA-AHMED
2      ahmed-chaudhry
3        Ali-chaudhry
4        ahmed-Akhtar
            ...
205        bilal-Khan
206        bilal-Khan
207       bilal-AHMED
208       FATIMA-butt
209     Zara-chaudhry
Name: Full_Name, Length: 210, dtype: object

In [66]:
df.ix(:)

SyntaxError: invalid syntax (3573782818.py, line 1)

In [70]:
with pd.option_context(
'display.max_rows',20):
    print(df)

    Employee_ID First_Name Last_Name  Gender     Age   Join_Date Department  \
0      EMP 0113     hassan   Qureshi       m  45 yrs  06-13-2022    finance
1      EMP 0055     FATIMA     AHMED       f     NaN   03-Jan-20         IT
2       EMP0158      ahmed  chaudhry    Male     NaN    22-04-20        H.R
3       emp0136        Ali  chaudhry  female      28  11-20-2022      sales
4        EMP134      ahmed    Akhtar       M     NaN  06-21-2020      sales
..          ...        ...       ...     ...     ...         ...        ...
205     emp0130      bilal      Khan       M      38    11-07-20    Finance
206      EMP108      bilal      Khan  female  23 yrs  06-20-2020         it
207     EMP0095      bilal     AHMED    Male     NaN   02-Jan-23    FINANCE
208    EMP 0046     FATIMA      butt    Male  27 yrs    16-02-22      sales
209     EMP0126       Zara  chaudhry  female  34 yrs    29-09-23  marketing

           City  Salary_PKR         Phone                      Email  \
0     islamabad         NaN   03323308823                    missing
1       karachi  PKR 119892      -9122210   FATIMA.AHMED@HOTMAIL.COM
2    rawalpindi       80720           NaN                    missing
3    Rawalpindi      140154           NaN   ali.chaudhry @ gmail.com
4     islamabad         NaN   03348959963                        NaN
..          ...         ...           ...                        ...
205   Islamabad     148,092  0349-3270167   bilal. khan@outlook. com
206     karachi         NaN  0313-8763551     BILAL.KHAN@OUTLOOK.COM
207      LAHORE       81728   03222924992  bilal. ahmed@hotmail. com
208     KARACHI     125,562           NaN      FATIMA.BUTT@GMAIL.COM
209      lahore      148816  0329-4115268                    missing

    Performance_Score  Unnamed: 12       Full_Name
0                   5          NaN  hassan-Qureshi
1                 NaN          NaN    FATIMA-AHMED
2                 NaN          NaN  ahmed-chaudhry
3                   5          NaN    Ali-chaudhry
4                 NaN          NaN    ahmed-Akhtar
..                ...          ...             ...
205               NaN          NaN      bilal-Khan
206               NaN          NaN      bilal-Khan
207         not rated          NaN     bilal-AHMED
208         not rated          NaN     FATIMA-butt
209                 1          NaN   Zara-chaudhry

[210 rows x 14 columns]

In [75]:
df.sort_values('Salary_PKR')

,Employee_ID,First_Name,Last_Name,Gender,Age,Join_Date,Department,City,Salary_PKR,Phone,Email,Performance_Score,Unnamed: 12,Full_Name
108,EMP64,Ali,chaudhry,Male,22 yrs,18-Sep-20,I.T,lahore,"100,343",03452512198,missing,not rated,NaN,Ali-chaudhry
64,EMP0089,usman,SHEIKH,f,NaN,12-Dec-20,marketing,karachi,100479,NaN,usman.sheikh@hotmail.com,not rated,NaN,usman-SHEIKH
33,EMP 0105,usman,SHEIKH,M,38 yrs,28-Aug-20,Sales,lahore,106171,-4473890,missing,NaN,NaN,usman-SHEIKH
66,EMP 0143,usman,Qureshi,male,NaN,31-03-21,finance,LAHORE,106877,-9092655,usman. qureshi@outlook. com,not rated,NaN,usman-Qureshi
52,emp0063,ahmed,butt,MALE,NaN,05-Jun-23,H.R,Lahore,107734,-3007537,NaN,NaN,NaN,ahmed-butt
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,EMP52,Zara,butt,female,NaN,09-03-22,H.R,rawalpindi,NaN,not provided,zara.butt@gmail.com,3.7,NaN,Zara-butt
191,EMP 0033,FATIMA,SHEIKH,Female,NaN,06-12-21,Marketing,Lahore,NaN,0345-4186946,fatima.sheikh @ gmail.com,NaN,NaN,FATIMA-SHEIKH
198,EMP59,FATIMA,Khan,female,37,06-Jul-21,it,Rawalpindi,NaN,0323-3077016,fatima. khan@yahoo. com,NaN,NaN,FATIMA-Khan
201,emp0037,Zara,Mirza,Female,NaN,02-10-20,finance,Islamabad,NaN,0316 1075267,zara.mirza @ outlook.com,3.4,NaN,Zara-Mirza
206,EMP108,bilal,Khan,female,23 yrs,06-20-2020,it,karachi,NaN,0313-8763551,BILAL.KHAN@OUTLOOK.COM,NaN,NaN,bilal-Khan

In [77]:
df['Department']=df['Department'].str.upper()

In [78]:
df.Department.head(10)

0      FINANCE
1           IT
2          H.R
3        SALES
4        SALES
5          H.R
6    MARKETING
7           HR
8      FINANCE
9      FINANCE
Name: Department, dtype: object

In [79]:
s=pd.Series([1,2,3,4,5,6,7,8,9])

In [81]:
s.pct_change()

0         NaN
1    1.000000
2    0.500000
3    0.333333
4    0.250000
5    0.200000
6    0.166667
7    0.142857
8    0.125000
dtype: float64

In [91]:
# print(s.axes)
# print(s.index)
df.columns

Index(['Employee_ID', 'First_Name', 'Last_Name', 'Gender', 'Age', 'Join_Date',
       'Department', 'City', 'Salary_PKR', 'Phone', 'Email',
       'Performance_Score', 'Unnamed: 12', 'Full_Name'],
      dtype='object')

In [98]:
s1=pd.Series([10,20,30,40,50,60,70,80,90])

In [99]:
s.cov(s1)

75.0

In [100]:
s.corr(s1)

1.0

In [102]:
s.rank(ascending=False)

0    9.0
1    8.0
2    7.0
3    6.0
4    5.0
5    4.0
6    3.0
7    2.0
8    1.0
dtype: float64

In [19]:
s2=pd.Series([1,2,2,2,3,4,5,6,7,8,9])

TypeError: 'list' object is not callable

In [106]:
s2.rank(method='dense')

0     1.0
1     2.0
2     2.0
3     2.0
4     3.0
     ...
6     5.0
7     6.0
8     7.0
9     8.0
10    9.0
Length: 11, dtype: float64

In [125]:
df['rank'] = df.groupby('Department')['Salary'].rank(
    ascending=False,
    method='dense'
)

top3 = df[df['rank'] <= 3]

In [121]:
df['Salary']=df['Salary_PKR'].str.replace('PKR',' ')

In [123]:
df['Salary']=df['Salary'].str.strip()

In [124]:
df['Salary']

0          NaN
1       119892
2        80720
3       140154
4          NaN
        ...
205    148,092
206        NaN
207      81728
208    125,562
209     148816
Name: Salary, Length: 210, dtype: object

In [133]:
df.sort_values(by='rank').head(20)

,Employee_ID,First_Name,Last_Name,Gender,Age,Join_Date,Department,City,Salary_PKR,Phone,Email,Performance_Score,Unnamed: 12,Full_Name,rank,Salary
193,EMP 0148,hassan,malik,MALE,43 yrs,17-Nov-23,I.T,rawalpindi,"96,827",0323-3883639,hassan.malik@yahoo.com,NaN,NaN,hassan-malik,1.0,"96,827"
121,EMP 0006,FATIMA,chaudhry,MALE,NaN,15-01-21,H.R,islamabad,"95,697",0310 1799898,fatima. chaudhry@yahoo. com,4,NaN,FATIMA-chaudhry,1.0,"95,697"
28,emp0010,bilal,butt,Male,unknown,18-02-21,FINANCE,Islamabad,"98,432",not provided,BILAL.BUTT@OUTLOOK.COM,4,NaN,bilal-butt,1.0,"98,432"
101,EMP0072,Ali,SHEIKH,m,NaN,10-22-2022,MARKETING,rawalpindi,90709,03128929215,missing,NaN,NaN,Ali-SHEIKH,1.0,90709
162,EMP26,MARIA,Akhtar,m,NaN,08-26-2020,IT,Islamabad,PKR 99621,03141557516,maria.akhtar @ hotmail.com,NaN,NaN,MARIA-Akhtar,1.0,99621
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,EMP0054,MARIA,malik,Male,25,09-17-2021,SALES,rawalpindi,PKR 91513,0313 3296643,NaN,NaN,NaN,MARIA-malik,3.0,91513
60,EMP 0070,FATIMA,SHEIKH,F,NaN,05-04-21,I.T,rawalpindi,62527,03343875647,fatima.sheikh @ yahoo.com,2.5,NaN,FATIMA-SHEIKH,3.0,62527
124,EMP 0047,Zara,AHMED,f,unknown,05-02-22,FINANCE,KARACHI,93370,-3982728,NaN,5,NaN,Zara-AHMED,3.0,93370
2,EMP0158,ahmed,chaudhry,Male,NaN,22-04-20,H.R,rawalpindi,80720,NaN,missing,NaN,NaN,ahmed-chaudhry,3.0,80720
83,EMP58,ahmed,HUSSAIN,Male,33 yrs,05-Feb-21,IT,rawalpindi,"90,701",03146947076,NaN,4.3,NaN,ahmed-HUSSAIN,3.0,"90,701"

In [129]:
df[df['rank'] <= 3]

,Employee_ID,First_Name,Last_Name,Gender,Age,Join_Date,Department,City,Salary_PKR,Phone,Email,Performance_Score,Unnamed: 12,Full_Name,rank,Salary
2,EMP0158,ahmed,chaudhry,Male,NaN,22-04-20,H.R,rawalpindi,80720,NaN,missing,NaN,NaN,ahmed-chaudhry,3.0,80720
20,EMP 0101,Sara,Mirza,female,NaN,05-06-20,SALES,LAHORE,PKR 97838,0325-1198389,sara. mirza@hotmail. com,NaN,NaN,Sara-Mirza,1.0,97838
28,emp0010,bilal,butt,Male,unknown,18-02-21,FINANCE,Islamabad,"98,432",not provided,BILAL.BUTT@OUTLOOK.COM,4,NaN,bilal-butt,1.0,"98,432"
60,EMP 0070,FATIMA,SHEIKH,F,NaN,05-04-21,I.T,rawalpindi,62527,03343875647,fatima.sheikh @ yahoo.com,2.5,NaN,FATIMA-SHEIKH,3.0,62527
74,EMP 0188,FATIMA,AHMED,male,NaN,05-28-2021,H.R,KARACHI,81153,0320 7597931,NaN,NaN,NaN,FATIMA-AHMED,2.0,81153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,emp0165,ahmed,Mirza,Female,unknown,10-Mar-21,I.T,Rawalpindi,"87,425",03151484250,NaN,not rated,NaN,ahmed-Mirza,2.0,"87,425"
187,EMP0054,MARIA,malik,Male,25,09-17-2021,SALES,rawalpindi,PKR 91513,0313 3296643,NaN,NaN,NaN,MARIA-malik,3.0,91513
193,EMP 0148,hassan,malik,MALE,43 yrs,17-Nov-23,I.T,rawalpindi,"96,827",0323-3883639,hassan.malik@yahoo.com,NaN,NaN,hassan-malik,1.0,"96,827"
194,EMP 0073,FATIMA,AHMED,f,NaN,09-05-23,FINANCE,islamabad,95354,03194634273,fatima.ahmed @ outlook.com,1.5,NaN,FATIMA-AHMED,2.0,95354
195,emp0192,nadia,butt,MALE,NaN,12-02-20,IT,KARACHI,"92,778",0314-6864282,missing,3,NaN,nadia-butt,2.0,"92,778"

In [2]:

np.random.seed(42)

dates = pd.date_range(start='2025-01-01', periods=30)

df1 = pd.DataFrame({
    'Date': dates,
    'Sales': np.random.randint(100, 1000, 30),
    'Profit': np.random.randint(20, 250, 30),
    'Orders': np.random.randint(10, 80, 30)
})

df1

         Date  Sales  Profit  Orders
0  2025-01-01    202     180      69
1  2025-01-02    535     223      23
2  2025-01-03    960      77      18
3  2025-01-04    370      41      62
4  2025-01-05    206     108      11
5  2025-01-06    171      68      69
6  2025-01-07    800     238      53
7  2025-01-08    120      78      17
8  2025-01-09    714     189      56
9  2025-01-10    221     239      44
10 2025-01-11    566     207      45
11 2025-01-12    314     227      59
12 2025-01-13    430      34      13
13 2025-01-14    558     209      11
14 2025-01-15    187     209      15
15 2025-01-16    472     194      63
16 2025-01-17    199     209      13
17 2025-01-18    971      70      63
18 2025-01-19    763     127      72
19 2025-01-20    230      74      27
20 2025-01-21    761      83      53
21 2025-01-22    408     150      43
22 2025-01-23    869     248      71
23 2025-01-24    443      70      23
24 2025-01-25    591     154      57
25 2025-01-26    513      40      24
26 2025-01-27    905      92      71
27 2025-01-28    485     186      49
28 2025-01-29    291      37      62
29 2025-01-30    376     151      33

In [138]:
df1['Sales'].expanding().sum()

0       202.0
1       737.0
2      1697.0
3      2067.0
4      2273.0
       ...
25    12574.0
26    13479.0
27    13964.0
28    14255.0
29    14631.0
Name: Sales, Length: 30, dtype: float64

In [142]:
pd.set_option('display.max_rows',30)
df1['Sales'].rolling(3).mean()

0            NaN
1            NaN
2     565.666667
3     621.666667
4     512.000000
5     249.000000
6     392.333333
7     363.666667
8     544.666667
9     351.666667
10    500.333333
11    367.000000
12    436.666667
13    434.000000
14    391.666667
15    405.666667
16    286.000000
17    547.333333
18    644.333333
19    654.666667
20    584.666667
21    466.333333
22    679.333333
23    573.333333
24    634.333333
25    515.666667
26    669.666667
27    634.333333
28    560.333333
29    384.000000
Name: Sales, dtype: float64

In [149]:
(df1['Sales'].rolling(7).sum())

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
5        NaN
6     3244.0
7     3162.0
8     3341.0
9     2602.0
10    2798.0
11    2906.0
12    3165.0
13    2923.0
14    2990.0
15    2748.0
16    2726.0
17    3131.0
18    3580.0
19    3380.0
20    3583.0
21    3804.0
22    4201.0
23    4445.0
24    4065.0
25    3815.0
26    4490.0
27    4214.0
28    4097.0
29    3604.0
Name: Sales, dtype: float64

In [151]:
df1['Sales'].ewm(span=5).mean()

0     202.000000
1     401.800000
2     666.210526
3     543.169231
4     413.734597
5     325.036090
6     493.199611
7     363.748771
8     483.617234
9     394.533305
10    452.357375
11    405.880033
12    413.961547
13    462.139397
14    370.216344
15    404.195961
16    335.727815
17    547.628590
18    619.451459
19    489.595255
20    580.081644
21    522.713429
22    638.152572
23    573.097850
24    579.065470
25    557.043065
26    673.030752
27    610.353099
28    503.901233
29    461.267266
Name: Sales, dtype: float64

In [1]:
import pandas as pd
import numpy as np

In [3]:
df1

         Date  Sales  Profit  Orders
0  2025-01-01    202     180      69
1  2025-01-02    535     223      23
2  2025-01-03    960      77      18
3  2025-01-04    370      41      62
4  2025-01-05    206     108      11
5  2025-01-06    171      68      69
6  2025-01-07    800     238      53
7  2025-01-08    120      78      17
8  2025-01-09    714     189      56
9  2025-01-10    221     239      44
10 2025-01-11    566     207      45
11 2025-01-12    314     227      59
12 2025-01-13    430      34      13
13 2025-01-14    558     209      11
14 2025-01-15    187     209      15
15 2025-01-16    472     194      63
16 2025-01-17    199     209      13
17 2025-01-18    971      70      63
18 2025-01-19    763     127      72
19 2025-01-20    230      74      27
20 2025-01-21    761      83      53
21 2025-01-22    408     150      43
22 2025-01-23    869     248      71
23 2025-01-24    443      70      23
24 2025-01-25    591     154      57
25 2025-01-26    513      40      24
26 2025-01-27    905      92      71
27 2025-01-28    485     186      49
28 2025-01-29    291      37      62
29 2025-01-30    376     151      33

In [24]:
r=(df1[['Sales','Profit']].rolling(window=3))

In [25]:
r.aggregate(np.sum)

C:\Users\PMLS\AppData\Local\Temp\ipykernel_18384\2653744253.py:1: FutureWarning: The provided callable <function sum at 0x0000019C2A851D00> is currently using Rolling.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  r.aggregate(np.sum)

     Sales  Profit
0      NaN     NaN
1      NaN     NaN
2   1697.0   480.0
3   1865.0   341.0
4   1536.0   226.0
5    747.0   217.0
6   1177.0   414.0
7   1091.0   384.0
8   1634.0   505.0
9   1055.0   506.0
10  1501.0   635.0
11  1101.0   673.0
12  1310.0   468.0
13  1302.0   470.0
14  1175.0   452.0
15  1217.0   612.0
16   858.0   612.0
17  1642.0   473.0
18  1933.0   406.0
19  1964.0   271.0
20  1754.0   284.0
21  1399.0   307.0
22  2038.0   481.0
23  1720.0   468.0
24  1903.0   472.0
25  1547.0   264.0
26  2009.0   286.0
27  1903.0   318.0
28  1681.0   315.0
29  1152.0   374.0

In [26]:
r.aggregate([np.sum,np.mean])

C:\Users\PMLS\AppData\Local\Temp\ipykernel_18384\1148119447.py:1: FutureWarning: The provided callable <function sum at 0x0000019C2A851D00> is currently using Rolling.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  r.aggregate([np.sum,np.mean])
C:\Users\PMLS\AppData\Local\Temp\ipykernel_18384\1148119447.py:1: FutureWarning: The provided callable <function mean at 0x0000019C2A852DE0> is currently using Rolling.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  r.aggregate([np.sum,np.mean])

     Sales             Profit
       sum        mean    sum        mean
0      NaN         NaN    NaN         NaN
1      NaN         NaN    NaN         NaN
2   1697.0  565.666667  480.0  160.000000
3   1865.0  621.666667  341.0  113.666667
4   1536.0  512.000000  226.0   75.333333
5    747.0  249.000000  217.0   72.333333
6   1177.0  392.333333  414.0  138.000000
7   1091.0  363.666667  384.0  128.000000
8   1634.0  544.666667  505.0  168.333333
9   1055.0  351.666667  506.0  168.666667
10  1501.0  500.333333  635.0  211.666667
11  1101.0  367.000000  673.0  224.333333
12  1310.0  436.666667  468.0  156.000000
13  1302.0  434.000000  470.0  156.666667
14  1175.0  391.666667  452.0  150.666667
15  1217.0  405.666667  612.0  204.000000
16   858.0  286.000000  612.0  204.000000
17  1642.0  547.333333  473.0  157.666667
18  1933.0  644.333333  406.0  135.333333
19  1964.0  654.666667  271.0   90.333333
20  1754.0  584.666667  284.0   94.666667
21  1399.0  466.333333  307.0  102.333333
22  2038.0  679.333333  481.0  160.333333
23  1720.0  573.333333  468.0  156.000000
24  1903.0  634.333333  472.0  157.333333
25  1547.0  515.666667  264.0   88.000000
26  2009.0  669.666667  286.0   95.333333
27  1903.0  634.333333  318.0  106.000000
28  1681.0  560.333333  315.0  105.000000
29  1152.0  384.000000  374.0  124.666667

In [21]:
for i in [1,2,3,4,5,6,7]:
    print(i)

1
2
3
4
5
6
7

In [27]:
r.aggregate({'Sales':np.sum, 'Profit':np.mean})

C:\Users\PMLS\AppData\Local\Temp\ipykernel_18384\3791665426.py:1: FutureWarning: The provided callable <function sum at 0x0000019C2A851D00> is currently using Rolling.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  r.aggregate({'Sales':np.sum, 'Profit':np.mean})
C:\Users\PMLS\AppData\Local\Temp\ipykernel_18384\3791665426.py:1: FutureWarning: The provided callable <function mean at 0x0000019C2A852DE0> is currently using Rolling.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  r.aggregate({'Sales':np.sum, 'Profit':np.mean})

     Sales      Profit
0      NaN         NaN
1      NaN         NaN
2   1697.0  160.000000
3   1865.0  113.666667
4   1536.0   75.333333
5    747.0   72.333333
6   1177.0  138.000000
7   1091.0  128.000000
8   1634.0  168.333333
9   1055.0  168.666667
10  1501.0  211.666667
11  1101.0  224.333333
12  1310.0  156.000000
13  1302.0  156.666667
14  1175.0  150.666667
15  1217.0  204.000000
16   858.0  204.000000
17  1642.0  157.666667
18  1933.0  135.333333
19  1964.0   90.333333
20  1754.0   94.666667
21  1399.0  102.333333
22  2038.0  160.333333
23  1720.0  156.000000
24  1903.0  157.333333
25  1547.0   88.000000
26  2009.0   95.333333
27  1903.0  106.000000
28  1681.0  105.000000
29  1152.0  124.666667

In [39]:
df['Phone'].fillna(method='bfill')

C:\Users\PMLS\AppData\Local\Temp\ipykernel_18384\2934082686.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Phone'].fillna(method='bfill')

0       03323308823
1          -9122210
2       03348959963
3       03348959963
4       03348959963
           ...
205    0349-3270167
206    0313-8763551
207     03222924992
208    0329-4115268
209    0329-4115268
Name: Phone, Length: 210, dtype: object

In [40]:
np.random.seed(42)

df2 = pd.DataFrame({
    'Employee_ID': range(1001, 1031),
    'Employee_Name': [
        'Ali','Sara','Ahmed','Fatima','Bilal','Ayesha','Usman','Noor','Hamza','Zain',
        'Hina','Omar','Laiba','Saad','Iqra','Daniyal','Maham','Taha','Sana','Areeb',
        'Anas','Kiran','Abdullah','Maryam','Asad','Rabia','Huzaifa','Muneeb','Mehwish','Raza'
    ],
    'Department': np.random.choice(
        ['HR','IT','Finance','Marketing','Sales'],
        30
    ),
    'City': np.random.choice(
        ['Lahore','Karachi','Islamabad'],
        30
    ),
    'Gender': np.random.choice(
        ['Male','Female'],
        30
    ),
    'Experience': np.random.randint(1,11,30),
    'Salary': np.random.randint(40000,120001,30),
    'Bonus': np.random.randint(5000,25001,30),
    'Performance': np.random.choice(
        ['Excellent','Good','Average','Poor'],
        30
    )
})

df2

,Employee_ID,Employee_Name,Department,City,Gender,Experience,Salary,Bonus,Performance
0,1001,Ali,Marketing,Islamabad,Male,8,118603,14789,Average
1,1002,Sara,Sales,Karachi,Female,5,92256,21312,Excellent
2,1003,Ahmed,Finance,Karachi,Female,2,75222,16252,Excellent
3,1004,Fatima,Sales,Islamabad,Female,5,117373,7693,Excellent
4,1005,Bilal,Sales,Karachi,Female,8,119575,18931,Poor
5,1006,Ayesha,IT,Islamabad,Female,10,103335,8627,Excellent
6,1007,Usman,Finance,Islamabad,Female,9,50965,21157,Average
7,1008,Noor,Finance,Lahore,Female,9,64538,15173,Excellent
8,1009,Hamza,Finance,Islamabad,Female,1,110592,23047,Good
9,1010,Zain,Sales,Lahore,Female,9,48110,15230,Good
10,1011,Hina,Marketing,Islamabad,Female,7,119309,20707,Poor
11,1012,Omar,Finance,Islamabad,Female,9,67266,16494,Good
12,1013,Laiba,Sales,Lahore,Male,8,92992,6306,Average
13,1014,Saad,IT,Lahore,Male,1,46910,11776,Excellent
14,1015,Iqra,Marketing,Islamabad,Female,8,40206,14474,Poor
15,1016,Daniyal,IT,Karachi,Female,8,63419,12526,Excellent
16,1017,Maham,Marketing,Lahore,Female,3,90636,10530,Excellent
17,1018,Taha,Sales,Karachi,Female,1,90015,8748,Average
18,1019,Sana,HR,Karachi,Female,8,94268,18545,Good
19,1020,Areeb,Marketing,Karachi,Female,3,58141,5663,Good
20,1021,Anas,IT,Lahore,Female,3,111910,6998,Excellent
21,1022,Kiran,Sales,Karachi,Female,1,96044,12994,Poor
22,1023,Abdullah,Marketing,Lahore,Male,5,107214,22879,Good
23,1024,Maryam,HR,Karachi,Female,10,73827,8304,Poor
24,1025,Asad,HR,Islamabad,Male,7,95820,23237,Good
25,1026,Rabia,Finance,Islamabad,Female,10,102623,18808,Poor
26,1027,Huzaifa,Finance,Lahore,Female,9,115450,11585,Average
27,1028,Muneeb,IT,Islamabad,Male,7,62299,22675,Poor
28,1029,Mehwish,Marketing,Islamabad,Female,9,83585,24965,Average
29,1030,Raza,Marketing,Karachi,Male,8,104044,16649,Average

In [59]:
gg=df2.groupby(['Department','Gender'])

In [55]:
for name, group in gg:
    print(name)
    print("\n\n")
    print(group)
    print("\n\n")

Finance



    Employee_ID Employee_Name Department       City  Gender  Experience  \
2          1003         Ahmed    Finance    Karachi  Female           2
6          1007         Usman    Finance  Islamabad  Female           9
7          1008          Noor    Finance     Lahore  Female           9
8          1009         Hamza    Finance  Islamabad  Female           1
11         1012          Omar    Finance  Islamabad  Female           9
25         1026         Rabia    Finance  Islamabad  Female          10
26         1027       Huzaifa    Finance     Lahore  Female           9

    Salary  Bonus Performance
2    75222  16252   Excellent
6    50965  21157     Average
7    64538  15173   Excellent
8   110592  23047        Good
11   67266  16494        Good
25  102623  18808        Poor
26  115450  11585     Average



HR



    Employee_ID Employee_Name Department       City  Gender  Experience  \
18         1019          Sana         HR    Karachi  Female           8
23         1024        Maryam         HR    Karachi  Female          10
24         1025          Asad         HR  Islamabad    Male           7

    Salary  Bonus Performance
18   94268  18545        Good
23   73827   8304        Poor
24   95820  23237        Good



IT



    Employee_ID Employee_Name Department       City  Gender  Experience  \
5          1006        Ayesha         IT  Islamabad  Female          10
13         1014          Saad         IT     Lahore    Male           1
15         1016       Daniyal         IT    Karachi  Female           8
20         1021          Anas         IT     Lahore  Female           3
27         1028        Muneeb         IT  Islamabad    Male           7

    Salary  Bonus Performance
5   103335   8627   Excellent
13   46910  11776   Excellent
15   63419  12526   Excellent
20  111910   6998   Excellent
27   62299  22675        Poor



Marketing



    Employee_ID Employee_Name Department       City  Gender  Experience  \
0          1001           Ali  Marketing  Islamabad    Male           8
10         1011          Hina  Marketing  Islamabad  Female           7
14         1015          Iqra  Marketing  Islamabad  Female           8
16         1017         Maham  Marketing     Lahore  Female           3
19         1020         Areeb  Marketing    Karachi  Female           3
22         1023      Abdullah  Marketing     Lahore    Male           5
28         1029       Mehwish  Marketing  Islamabad  Female           9
29         1030          Raza  Marketing    Karachi    Male           8

    Salary  Bonus Performance
0   118603  14789     Average
10  119309  20707        Poor
14   40206  14474        Poor
16   90636  10530   Excellent
19   58141   5663        Good
22  107214  22879        Good
28   83585  24965     Average
29  104044  16649     Average



Sales



    Employee_ID Employee_Name Department       City  Gender  Experience  \
1          1002          Sara      Sales    Karachi  Female           5
3          1004        Fatima      Sales  Islamabad  Female           5
4          1005         Bilal      Sales    Karachi  Female           8
9          1010          Zain      Sales     Lahore  Female           9
12         1013         Laiba      Sales     Lahore    Male           8
17         1018          Taha      Sales    Karachi  Female           1
21         1022         Kiran      Sales    Karachi  Female           1

    Salary  Bonus Performance
1    92256  21312   Excellent
3   117373   7693   Excellent
4   119575  18931        Poor
9    48110  15230        Good
12   92992   6306     Average
17   90015   8748     Average
21   96044  12994        Poor

In [53]:
pd.set_option('display.max_columns', 60)

In [57]:
pd.get_option('display.max_columns')

20

In [61]:
gg.groups

{('Finance', 'Female'): [2, 6, 7, 8, 11, 25, 26], ('HR', 'Female'): [18, 23], ('HR', 'Male'): [24], ('IT', 'Female'): [5, 15, 20], ('IT', 'Male'): [13, 27], ('Marketing', 'Female'): [10, 14, 16, 19, 28], ('Marketing', 'Male'): [0, 22, 29], ('Sales', 'Female'): [1, 3, 4, 9, 17, 21], ('Sales', 'Male'): [12]}

In [68]:
grouped=df2.groupby('Department')

In [69]:
print(grouped.get_group('HR'))

    Employee_ID Employee_Name Department       City  Gender  Experience  \
18         1019          Sana         HR    Karachi  Female           8
23         1024        Maryam         HR    Karachi  Female          10
24         1025          Asad         HR  Islamabad    Male           7

    Salary  Bonus Performance
18   94268  18545        Good
23   73827   8304        Poor
24   95820  23237        Good

In [70]:
df2.sort_values(by='Salary', ascending=False)

,Employee_ID,Employee_Name,Department,City,Gender,Experience,Salary,Bonus,Performance
4,1005,Bilal,Sales,Karachi,Female,8,119575,18931,Poor
10,1011,Hina,Marketing,Islamabad,Female,7,119309,20707,Poor
0,1001,Ali,Marketing,Islamabad,Male,8,118603,14789,Average
3,1004,Fatima,Sales,Islamabad,Female,5,117373,7693,Excellent
26,1027,Huzaifa,Finance,Lahore,Female,9,115450,11585,Average
20,1021,Anas,IT,Lahore,Female,3,111910,6998,Excellent
8,1009,Hamza,Finance,Islamabad,Female,1,110592,23047,Good
22,1023,Abdullah,Marketing,Lahore,Male,5,107214,22879,Good
29,1030,Raza,Marketing,Karachi,Male,8,104044,16649,Average
5,1006,Ayesha,IT,Islamabad,Female,10,103335,8627,Excellent
25,1026,Rabia,Finance,Islamabad,Female,10,102623,18808,Poor
21,1022,Kiran,Sales,Karachi,Female,1,96044,12994,Poor
24,1025,Asad,HR,Islamabad,Male,7,95820,23237,Good
18,1019,Sana,HR,Karachi,Female,8,94268,18545,Good
12,1013,Laiba,Sales,Lahore,Male,8,92992,6306,Average
1,1002,Sara,Sales,Karachi,Female,5,92256,21312,Excellent
16,1017,Maham,Marketing,Lahore,Female,3,90636,10530,Excellent
17,1018,Taha,Sales,Karachi,Female,1,90015,8748,Average
28,1029,Mehwish,Marketing,Islamabad,Female,9,83585,24965,Average
2,1003,Ahmed,Finance,Karachi,Female,2,75222,16252,Excellent
23,1024,Maryam,HR,Karachi,Female,10,73827,8304,Poor
11,1012,Omar,Finance,Islamabad,Female,9,67266,16494,Good
7,1008,Noor,Finance,Lahore,Female,9,64538,15173,Excellent
15,1016,Daniyal,IT,Karachi,Female,8,63419,12526,Excellent
27,1028,Muneeb,IT,Islamabad,Male,7,62299,22675,Poor
19,1020,Areeb,Marketing,Karachi,Female,3,58141,5663,Good
6,1007,Usman,Finance,Islamabad,Female,9,50965,21157,Average
9,1010,Zain,Sales,Lahore,Female,9,48110,15230,Good
13,1014,Saad,IT,Lahore,Male,1,46910,11776,Excellent
14,1015,Iqra,Marketing,Islamabad,Female,8,40206,14474,Poor

In [73]:
grouped=df2.groupby('Department')

In [79]:
grouped[['Salary','Bonus']].agg([np.sum,np.mean,np.std])

C:\Users\PMLS\AppData\Local\Temp\ipykernel_18384\3750725294.py:1: FutureWarning: The provided callable <function sum at 0x0000019C2A851D00> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grouped[['Salary','Bonus']].agg([np.sum,np.mean,np.std])
C:\Users\PMLS\AppData\Local\Temp\ipykernel_18384\3750725294.py:1: FutureWarning: The provided callable <function mean at 0x0000019C2A852DE0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grouped[['Salary','Bonus']].agg([np.sum,np.mean,np.std])
C:\Users\PMLS\AppData\Local\Temp\ipykernel_18384\3750725294.py:1: FutureWarning: The provided callable <function std at 0x0000019C2A852F20> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  grouped[['Salary','Bonus']].agg([np.sum,np.mean,np.std])

            Salary                               Bonus                \
               sum          mean           std     sum          mean
Department
Finance     586656  83808.000000  25396.705016  122516  17502.285714
HR          263915  87971.666667  12274.195384   50086  16695.333333
IT          387873  77574.600000  28357.364833   62602  12520.400000
Marketing   721738  90217.250000  28551.513043  130656  16332.000000
Sales       656365  93766.428571  23558.451158   91214  13030.571429


                    std
Department
Finance     3847.626529
HR          7636.397864
IT          6109.941268
Marketing   6436.023506
Sales       5777.627652

In [ ]:
#new world now every commit will be verified askdmaklsmd